language: node_js
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules # NPM packages
    - $HOME/.npm # NPM packages

git:
  depth: 2

env:
 global:
  - GH_REF: "git@github.com:NewFuture/pac.git"
  - GH_BRANCH: "gh-pages"
  - BUILD_PATH: "_site/"
  - GIT_AUTHOR_NAME: "NewFuture"  
  - GIT_AUTHOR_EMAIL:  "${GIT_AUTHOR_NAME}@users.noreply.github.com"
  - GIT_COMMITTER_NAME: "${GIT_AUTHOR_NAME}"
  - GIT_COMMITTER_EMAIL: "${GIT_COMMITTER_NAME}@users.noreply.github.com"

install: true

before_script:
  - base64 -d <<< $RSAKEY > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git clone --depth=1 -b ${GH_BRANCH} "${GH_REF}" "${BUILD_PATH}"
  - npm i eslint@2.13.1 --cache-min 999999

script:
  - ./run.js
  - ./node_modules/eslint/bin/eslint.js _site/ --no-eslintrc --ext .js --ext .txt --ext .pac

after_success:
  - cd "$BUILD_PATH" 
  - git add .
  - git commit -m "auto build [skip ci]" && git push -f "${GH_REF}" ${GH_BRANCH}:${GH_BRANCH}


notifications:
  email:
    on_failure: change
    on_success: change
