name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_REF: "https://github.com/NewFuture/pac.git"
      GH_BRANCH: "gh-pages"
      BUILD_PATH: "_site/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ${{ runner.tool_cache }}/npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Checkout gp-pages branch
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_PATH}}
          ref: ${{env.GH_BRANCH}}

      - name: Install ESLint
        run: npm install eslint@2.13.1 --cache-min 999999

      - name: Run script
        run: ./run.js

      - name: Run ESLint
        run: ./node_modules/eslint/bin/eslint.js _site/ --no-eslintrc --ext .js --ext .txt --ext .pac

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          commit_message: Automated build
          # Optional. Local and remote branch name where commit is going to be pushed
          branch: ${{env.GH_BRANCH}}

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          # commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          # file_pattern: '*.php src/*.js tests/*.js'

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: ${{env.BUILD_PATH}}

          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          # commit_author: Author <actions@github.com> # defaults to "username <username@users.noreply.github.com>", where "username" belongs to the author of the commit that triggered the run


          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          # add_options: '-u'

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'        
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    
          # Optional. Skip internal call to `git checkout`
          skip_checkout: true
    
          
